uecode_qpush:
    aws_credentials:
        api_key: null
        api_token: null
        region: null
    cache:
        type: file
        id: null
        directory: null
    queues:
        default:
            delay_seconds: 0
            maximum_message_size: 262144
            message_retention_period: 345600
            visibility_timeout: 30
            receive_message_wait_time_seconds: 5
            use_sns: true
            subscribers:
                - { endpoint: http://example.com, protocol: http }
