parameters:
    uecode_qpush.registry.class: Uecode\Bundle\QPushBundle\Queue\QPushQueueRegistry

services:
### QPush Registry
    uecode_qpush.registry:
        class: %uecode_qpush.registry.class%
    uecode_qpush:
        alias: uecode_qpush.registry

### QPush Event Listeners
    uecode_qpush.controller_listener:
        class: Uecode\Bundle\QPushBundle\EventListener\AwsControllerListener
        arguments: [ @controller_resolver ]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, priority: 254 }
