parameters:
    uecode_qpush.registry.class: Uecode\Bundle\QPushBundle\QPushRegistry
    uecode_qpush.service.class: Uecode\Bundle\QPushBundle\Service\QPushService

services:
### QPush Registry
    uecode_qpush.registry:
        class: %uecode_qpush.registry.class%
    uecode_qpush:
        alias: uecode_qpush.registry

### QPush Service
    uecode_qpush.service:
        class: %uecode_qpush.service.class%
        abstract: true
        arguments:
            - null
            - null
            - null
            - @uecode_qpush.sqs_client
            - @uecode_qpush.sns_client

### QPush Event Listeners
    uecode_qpush.sns_request_listener:
        class: Uecode\Bundle\QPushBundle\EventListener\SnsRequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 254 }

### AWS Clients
    uecode_qpush.sns_client:
        class:              Aws\Sns\SnsClient
        factory_class:      Aws\Sns\SnsClient
        factory_method:     factory
        arguments: [ %aws.credentials% ]
        public: false

    uecode_qpush.sqs_client:
        class:              Aws\Sqs\SqsClient
        factory_class:      Aws\Sqs\SqsClient
        factory_method:     factory
        arguments: [ %aws.credentials% ]
        public: false
