language: php

php:
    - 5.5
    - 5.4
    - 5.6
    - 7.0
    - hhvm

env:
    - SYMFONY_VERSION=2.3.*
    - SYMFONY_VERSION=2.4.*
    - SYMFONY_VERSION=2.5.*
    - SYMFONY_VERSION=2.6.*

install:
    - travis_retry composer self-update
    - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
    - travis_retry composer install --prefer-source

script: phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
    webhooks: http://ue.hipchat.com/hubot/travis?room=Underground Elephant

matrix:
    allow_failures:
        - php: hhvm
        - php: 7.0

sudo: false

cache:
    directories:
        - $HOME/.composer/cache