language: php

php:
  - 5.5
  - 5.4

env:
    - SYMFONY_VERSION=2.3.*
    - SYMFONY_VERSION=2.4.*
    - SYMFONY_VERSION=2.5.*

before_script:
    - composer self-update
    - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
    - composer install --dev --prefer-source

script: phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
    webhooks: http://ue.hipchat.com/hubot/travis?room=Underground Elephant
