parameters:
    uecode_qpush.registry.class: Uecode\Bundle\QPushBundle\Provider\QPushProviderRegistry
    uecode_qpush.provider.ironmq: Uecode\Bundle\QPushBundle\Provider\IronMqProvider
    uecode_qpush.provider.aws: Uecode\Bundle\QPushBundle\Provider\AwsProvider

services:
### QPush Registry
    uecode_qpush.registry:
        class: %uecode_qpush.registry.class%
    uecode_qpush:
        alias: uecode_qpush.registry

### QPush Event Listeners
    uecode_qpush.controller_listener:
        class: Uecode\Bundle\QPushBundle\EventListener\RequestListener
        arguments: [ @event_dispatcher ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 254 }
