services:
    ### QPush Registry
    uecode_qpush.registry:
        class: %uecode_qpush.registry.class%
    uecode_qpush:
        alias: uecode_qpush.registry

    ### QPush Event Listeners
    uecode_qpush.request_listener:
        class: Uecode\Bundle\QPushBundle\EventListener\RequestListener
        arguments: [ @event_dispatcher, @uecode_qpush.logger ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 254 }

    ### QPush Logger
    uecode_qpush.logger:
        class: Symfony\Bridge\Monolog\Logger
        arguments: [qpush]
        calls:
             - [pushHandler, [@uecode_qpush.logger_handler]]

    uecode_qpush.logger_handler:
        class: Monolog\Handler\StreamHandler
        arguments: [%kernel.logs_dir%/%kernel.environment%.qpush.log, 200]
